### ISSUE TITLE
Extends default karma configuration

### ISSUE THREAD

**Issue by maxcleme** [cybrown/runpack#2]
Hi,

It seems that it is impossible to override the default karma configuration.

In fact, the default one is already overridden, but by an empty created one : 

https://github.com/cybrown/runpack/blob/master/lib/commands/test.js#L13

```javascript
var karmaOptions = {
    webpack: getWebpackConfiguration(webpackConfig)
};
```

Is there anyway to support this ? 

Moreover, using the params ```testReport``` leads to Error since the ```reporters``` array is not defined.

**Comment by cybrown** [comment]
You should be able to override the karma configuration by using the configureKarma callback exported in the karma.config.js file, just like the configureWebpack callback.

https://github.com/cybrown/runpack/blob/master/lib/util/start-karma.js#L13

Two parameters are given to this callback, the first one is the original karma configuration, and the second is the karma API.

You may mutate the configuration, or return a newly created object to get rid of the original configuration.

**Comment by maxcleme** [comment]
Nice, works perfectly ;)

Thanks :)
